name: Rodents of Unusual Size
title: The Fire Swamp
description: A collaborative site for the Oak Hills 5th Ward Youth
url: "https://rodents-of-unusual-size.github.io"
markdown: GFM
theme: jekyll-theme-dinky

collections:
  rouses:
    output: true

defaults:
  - scope:
      path: ""
      type: "rouses"
    values:
      layout: "rous"
